/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.tgbot.jooq.public_.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chat implements Serializable {

    private static final long serialVersionUID = -944461471;

    private Integer id;
    private Integer chatid;
    private String  name;
    private String  locale;

    public Chat() {}

    public Chat(Chat value) {
        this.id = value.id;
        this.chatid = value.chatid;
        this.name = value.name;
        this.locale = value.locale;
    }

    public Chat(
        Integer id,
        Integer chatid,
        String  name,
        String  locale
    ) {
        this.id = id;
        this.chatid = chatid;
        this.name = name;
        this.locale = locale;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getChatid() {
        return this.chatid;
    }

    public void setChatid(Integer chatid) {
        this.chatid = chatid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLocale() {
        return this.locale;
    }

    public void setLocale(String locale) {
        this.locale = locale;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Chat (");

        sb.append(id);
        sb.append(", ").append(chatid);
        sb.append(", ").append(name);
        sb.append(", ").append(locale);

        sb.append(")");
        return sb.toString();
    }
}
