CREATE TABLE PUBLIC.Chat
(
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ChatID INT NOT NULL,
    Name VARCHAR2(100) NOT NULL,
    Locale VARCHAR2(10)
);
CREATE UNIQUE INDEX Chat_ChatID_uindex ON PUBLIC.Chat (ChatID);