CREATE TABLE PUBLIC.Tag
(
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    rid VARCHAR2(40) NOT NULL,
    zhTw VARCHAR2(100),
    zhCn VARCHAR2(100),
    en VARCHAR2(100),
    jp VARCHAR2(100)
);
CREATE UNIQUE INDEX Tag_id_uindex ON PUBLIC.Tag (id);
CREATE UNIQUE INDEX Tag_rid_uindex ON PUBLIC.Tag (rid);