/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.tgbot.jooq.public_;


import com.sukitsuki.tgbot.jooq.public_.tables.Chatrecord;
import com.sukitsuki.tgbot.jooq.public_.tables.records.ChatrecordRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ChatrecordRecord, Long> IDENTITY_CHATRECORD = Identities0.IDENTITY_CHATRECORD;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatrecordRecord> CONSTRAINT_BB = UniqueKeys0.CONSTRAINT_BB;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<ChatrecordRecord, Long> IDENTITY_CHATRECORD = createIdentity(Chatrecord.CHATRECORD, Chatrecord.CHATRECORD.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ChatrecordRecord> CONSTRAINT_BB = createUniqueKey(Chatrecord.CHATRECORD, "CONSTRAINT_BB", Chatrecord.CHATRECORD.ID);
    }
}
