/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.tgbot.jooq.public_;


import com.sukitsuki.tgbot.jooq.public_.tables.Chat;
import com.sukitsuki.tgbot.jooq.public_.tables.Tag;
import com.sukitsuki.tgbot.jooq.public_.tables.records.ChatRecord;
import com.sukitsuki.tgbot.jooq.public_.tables.records.TagRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ChatRecord, Integer> IDENTITY_CHAT = Identities0.IDENTITY_CHAT;
    public static final Identity<TagRecord, Integer> IDENTITY_TAG = Identities0.IDENTITY_TAG;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CONSTRAINT_1 = UniqueKeys0.CONSTRAINT_1;
    public static final UniqueKey<TagRecord> CONSTRAINT_14 = UniqueKeys0.CONSTRAINT_14;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<ChatRecord, Integer> IDENTITY_CHAT = createIdentity(Chat.CHAT, Chat.CHAT.ID);
        public static Identity<TagRecord, Integer> IDENTITY_TAG = createIdentity(Tag.TAG, Tag.TAG.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ChatRecord> CONSTRAINT_1 = createUniqueKey(Chat.CHAT, "CONSTRAINT_1", Chat.CHAT.ID);
        public static final UniqueKey<TagRecord> CONSTRAINT_14 = createUniqueKey(Tag.TAG, "CONSTRAINT_14", Tag.TAG.ID);
    }
}
