/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.tgbot.jooq.public_;


import com.sukitsuki.tgbot.jooq.DefaultCatalog;
import com.sukitsuki.tgbot.jooq.public_.tables.Chat;
import com.sukitsuki.tgbot.jooq.public_.tables.Tag;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1113096938;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.CHAT</code>.
     */
    public final Chat CHAT = com.sukitsuki.tgbot.jooq.public_.tables.Chat.CHAT;

    /**
     * The table <code>PUBLIC.TAG</code>.
     */
    public final Tag TAG = com.sukitsuki.tgbot.jooq.public_.tables.Tag.TAG;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.SYSTEM_SEQUENCE_1E92B028_B915_4E52_AA81_DE5367DBCD7F,
            Sequences.SYSTEM_SEQUENCE_FC277016_5B57_42B6_8242_32BCBAC8CAAA);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Chat.CHAT,
            Tag.TAG);
    }
}
