/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.tgbot.jooq.public_;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_46470562_D2B1_4D58_99B1_BDA8502CF105</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_46470562_D2B1_4D58_99B1_BDA8502CF105 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_46470562_D2B1_4D58_99B1_BDA8502CF105", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
