/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.tgbot.jooq.public_;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_1E92B028_B915_4E52_AA81_DE5367DBCD7F</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_1E92B028_B915_4E52_AA81_DE5367DBCD7F = new SequenceImpl<Long>("SYSTEM_SEQUENCE_1E92B028_B915_4E52_AA81_DE5367DBCD7F", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_FC277016_5B57_42B6_8242_32BCBAC8CAAA</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_FC277016_5B57_42B6_8242_32BCBAC8CAAA = new SequenceImpl<Long>("SYSTEM_SEQUENCE_FC277016_5B57_42B6_8242_32BCBAC8CAAA", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
