/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.tgbot.jooq.public_;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_1A2418EA_9CE7_4880_AFCA_CC289BF6F6C9</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_1A2418EA_9CE7_4880_AFCA_CC289BF6F6C9 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_1A2418EA_9CE7_4880_AFCA_CC289BF6F6C9", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_62E81A94_5029_4514_B434_D015856DA09E</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_62E81A94_5029_4514_B434_D015856DA09E = new SequenceImpl<Long>("SYSTEM_SEQUENCE_62E81A94_5029_4514_B434_D015856DA09E", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
