/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.tgbot.jooq.public_;


import com.sukitsuki.tgbot.jooq.public_.tables.Chatrecord;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.CHATRECORD</code>.
     */
    public static final Chatrecord CHATRECORD = com.sukitsuki.tgbot.jooq.public_.tables.Chatrecord.CHATRECORD;
}
