/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.tgbot.jooq.public_;


import com.sukitsuki.tgbot.jooq.public_.tables.Chat;
import com.sukitsuki.tgbot.jooq.public_.tables.Tag;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.CHAT</code>.
     */
    public static final Chat CHAT = com.sukitsuki.tgbot.jooq.public_.tables.Chat.CHAT;

    /**
     * The table <code>PUBLIC.TAG</code>.
     */
    public static final Tag TAG = com.sukitsuki.tgbot.jooq.public_.tables.Tag.TAG;
}
