/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.tgbot.jooq.public_.tables.records;


import com.sukitsuki.tgbot.jooq.public_.tables.Chatrecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatrecordRecord extends UpdatableRecordImpl<ChatrecordRecord> implements Record4<Long, Integer, String, String> {

    private static final long serialVersionUID = 408751401;

    /**
     * Setter for <code>PUBLIC.CHATRECORD.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CHATRECORD.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CHATRECORD.CHATID</code>.
     */
    public void setChatid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CHATRECORD.CHATID</code>.
     */
    public Integer getChatid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CHATRECORD.NAME</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CHATRECORD.NAME</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.CHATRECORD.LOCALE</code>.
     */
    public void setLocale(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.CHATRECORD.LOCALE</code>.
     */
    public String getLocale() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Integer, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Integer, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Chatrecord.CHATRECORD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Chatrecord.CHATRECORD.CHATID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Chatrecord.CHATRECORD.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Chatrecord.CHATRECORD.LOCALE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getChatid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLocale();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatrecordRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatrecordRecord value2(Integer value) {
        setChatid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatrecordRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatrecordRecord value4(String value) {
        setLocale(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatrecordRecord values(Long value1, Integer value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatrecordRecord
     */
    public ChatrecordRecord() {
        super(Chatrecord.CHATRECORD);
    }

    /**
     * Create a detached, initialised ChatrecordRecord
     */
    public ChatrecordRecord(Long id, Integer chatid, String name, String locale) {
        super(Chatrecord.CHATRECORD);

        set(0, id);
        set(1, chatid);
        set(2, name);
        set(3, locale);
    }
}
